

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUEST = "USER_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGGEDIN_USER_REQUEST = "LOGGEDIN_USER_REQUEST";
export const LOGGEDIN_USER_SUCCESS = "LOGGEDIN_USER_SUCCESS";
export const LOGGEDIN_USER_FAILED = "LOGGEDIN_USER_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

