

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUEST = "USER_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGGEDIN_USER_REQUEST = "LOGGEDIN_USER_REQUEST";
export const LOGGEDIN_USER_SUCCESS = "LOGGEDIN_USER_SUCCESS";
export const LOGGEDIN_USER_FAILED = "LOGGEDIN_USER_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";
export const USER_PROFILE_PHOTO_UPDATE = "USER_PROFILE_PHOTO_UPDATE";

export const GET_USERS_REQ = "GET_USERS_REQ";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

